### ISSUE TITLE
More Errors faced in running repair.py and manual fix not working

### ISSUE THREAD

**Issue by TheIndianProgrammer** [phuze/windows-10-missing-search-icons#10]
Hey!, I started to face the same issues with my Start Menu when I installed Google Drive for desktop, I Uninstalled Google Drive for desktop and restarted my computer but it didn't fix the issue. I have downloaded the “windows-10-missing-search-icons.zip”, i ran the repair.py and got the same error which was faced in Issue "Error when executing repair.py" after I changed the directory to the appropriate one in Line 24 of the python file as advised in the Issue, I get a different error now- 

______________________________________________________
```
Warning (from warnings module):
  File "C:\Users\user\Desktop\windows-10-missing-search-icons-master\windows-10-missing-search-icons-master\repair\repair.py", line 9
    from distutils.dir_util import copy_tree as copyDirectory
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives

fetching username...
copying files…

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Desktop\\windows-10-missing-search-icons-master\\windows-10-missing-search-icons-master\\repair\\_output\\raw\\C__Users_user_AppData_Local_Apps_2_0_A1VN1ZVT_HJ8_420WXPAB_GH4_smrf__vsto_ca7cf396c323c882_0001_0000_f6be6f4c6d83840a_DeployedTemplate_NodeXLGraph_xltx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\windows-10-missing-search-icons-master\windows-10-missing-search-icons-master\repair\repair.py", line 90, in <module>
    main()
  File "C:\Users\user\Desktop\windows-10-missing-search-icons-master\windows-10-missing-search-icons-master\repair\repair.py", line 40, in main
    copyDirectory(iconCache, rawStore)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\dir_util.py", line 161, in copy_tree
    copy_file(src_name, dst_name, preserve_mode,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\distutils\file_util.py", line 43, in _copy_file_contents
    raise DistutilsFileError(
distutils.errors.DistutilsFileError: could not create 'C:\Users\user\Desktop\windows-10-missing-search-icons-master\windows-10-missing-search-icons-master\repair\_output\raw\C__Users_user_AppData_Local_Apps_2_0_A1VN1ZVT_HJ8_420WXPAB_GH4_smrf__vsto_ca7cf396c323c882_0001_0000_f6be6f4c6d83840a_DeployedTemplate_NodeXLGraph_xltx': No such file or directory
```

_________________________________________________________

After this, i tried to fix the Microsoft News icon Manually 

1) So I went to the WindowsApp folder `C:/Program Files/WindowsApps`

2) I found multiple folders that had Bing News in their name 

![image](https://user-images.githubusercontent.com/64490665/158324001-d15953ce-5345-4096-9e22-d66cea8a4138.png)

I decided to go to:
`“Microsoft.BingNews_4.54.22741.0_neutral_split.scale-125_8wekyb3d8bbwe\Assets\AppTiles”`

3) I copied and pasted the file named `“NewsStoreLogo.scale-125.png”` to the Desktop and renamed it to `“Microsoft.BingNews_4.54.22741.0_neutral_split.scale-125_8wekyb3d8bbwe”`

![image](https://user-images.githubusercontent.com/64490665/158325430-242e9972-1f2b-4957-9196-7086b96df470.png)

4) I then moved this file to 
`“C:\Users\user\AppData\Local\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache\125”`

5) I then restarted win explorer and unfortunately, nothing changed

![image](https://user-images.githubusercontent.com/64490665/158325512-1d7649dd-14de-49f3-ad84-0c783e9cf7f8.png)

Am I doing something wrong? Thanks!!,

**Comment by TheIndianProgrammer** [comment]
Before I found this really wonderful guide, I tried to fix the issue by adding a shortcut of the programs to the Global Start Menu Programs folder `%ProgramData%\Microsoft\Windows\Start Menu\Programs` (interestingly when I pasted those shortcuts in the User start menu folder `%AppData%\Microsoft\Windows\Start Men\Programs` i didn't get the same result), the icons of the program were off, and I faced problems like icons becoming blank when I pin them to the taskbar.
